[package]
name = "mathcompile"
version = "0.2.0"
edition = "2024"
description = "High-performance symbolic mathematics with final tagless design, egglog optimization, and Rust hot-loading compilation"
license = "Apache-2.0"
repository = "https://github.com/chad-measures/measures"
keywords = ["symbolic", "mathematics", "rust-codegen", "final-tagless", "optimization"]
categories = ["mathematics", "science", "compilers"]

[dependencies]
# Core numeric traits for generic operations
num-traits = "0.2"

# Error handling
thiserror = "2.0.12"

# JIT compilation with Cranelift (optional)
cranelift = { version = "0.120.0", optional = true }
cranelift-jit = { version = "0.120.0", optional = true }
cranelift-module = { version = "0.120.0", optional = true }
cranelift-codegen = { version = "0.120.0", optional = true }
cranelift-frontend = { version = "0.120.0", optional = true }
target-lexicon = { version = "0.13.2", optional = true }

# Serialization support
serde = { version = "1.0", features = ["derive"], optional = true }

# Symbolic optimization with egglog
egglog = { version = "0.4", optional = true }

# Dynamic library loading for Rust codegen backend
dlopen2 = "0.8"

# For performance comparisons
ad_trait = { version = "0.1", optional = true }
ordered-float = "5.0.0"

# Special mathematical functions (gamma, beta, bessel, etc.)
special = { version = "0.11", optional = true }


[features]
default = ["optimization"]
optimization = ["egglog"]
special = ["dep:special"]  # Enable special mathematical functions (gamma, beta, bessel, etc.)
linear_algebra = []  # Enable linear algebra operations and matrix support
logexp = []  # Enable logarithmic and exponential function extensions
special_functions = ["special"]  # Enable special mathematical functions (gamma, beta, bessel, etc.)
full = ["optimization", "linear_algebra", "special_functions", "logexp"]  # All features enabled
cranelift = ["dep:cranelift", "dep:cranelift-jit", "dep:cranelift-module", "dep:cranelift-codegen", "dep:cranelift-frontend", "dep:target-lexicon"]
ad_trait = ["dep:ad_trait"]
all = ["optimization", "cranelift", "ad_trait", "special_functions", "logexp", "linear_algebra"]

# Legacy feature aliases for backward compatibility
symbolic = ["optimization"]
jit = ["cranelift"]

[dev-dependencies]
criterion = { version = "0.6.0", features = ["html_reports"] }
divan = "0.1"
proptest = "1.5"

[[bench]]
name = "expression_optimization"
harness = false

[[bench]]
name = "simple_optimization"
harness = false

[[bench]]
name = "cranelift_vs_rust"
harness = false

 