[package]
name = "mathjit"
version = "0.1.0"
edition = "2021"
description = "High-performance symbolic mathematics with final tagless design, egglog optimization, and Rust hot-loading compilation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chad-measures/measures"
keywords = ["symbolic", "mathematics", "rust-codegen", "final-tagless", "optimization"]
categories = ["mathematics", "science", "compilers"]

[dependencies]
# Core numeric traits for generic operations
num-traits = "0.2"

# Error handling
thiserror = "1.0"

# JIT compilation with Cranelift (optional)
cranelift = { version = "0.112", optional = true }
cranelift-jit = { version = "0.112", optional = true }
cranelift-module = { version = "0.112", optional = true }
cranelift-codegen = { version = "0.112", optional = true }
cranelift-frontend = { version = "0.112", optional = true }
target-lexicon = { version = "0.12", optional = true }

# Serialization support
serde = { version = "1.0", features = ["derive"], optional = true }

# Symbolic optimization with egglog
egglog = { version = "0.4", optional = true }

# For performance comparisons
ad_trait = { version = "0.1", optional = true }

[features]
default = ["optimization"]
optimization = ["dep:egglog"]
cranelift = ["dep:cranelift", "dep:cranelift-jit", "dep:cranelift-module", "dep:cranelift-codegen", "dep:cranelift-frontend", "dep:target-lexicon"]
ad_trait = ["dep:ad_trait"]
all = ["optimization", "cranelift", "ad_trait"]

# Legacy feature aliases for backward compatibility
symbolic = ["optimization"]
jit = ["cranelift"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
libloading = "0.8"
divan = "0.1"

[[bench]]
name = "expression_optimization"
harness = false

[[bench]]
name = "simple_optimization"
harness = false

[[bench]]
name = "cranelift_vs_rust"
harness = false

 