[package]
name = "mathjit"
version = "0.1.0"
edition = "2021"
description = "High-performance symbolic mathematics with final tagless design, egglog optimization, and Cranelift JIT compilation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/chad-measures/measures"
keywords = ["symbolic", "mathematics", "jit", "final-tagless", "optimization"]
categories = ["mathematics", "science", "compilers"]

[dependencies]
# Core numeric traits for generic operations
num-traits = "0.2"

# Error handling
thiserror = "1.0"

# JIT compilation with Cranelift
cranelift = "0.112"
cranelift-jit = "0.112"
cranelift-module = "0.112"
cranelift-codegen = "0.112"
cranelift-frontend = "0.112"
target-lexicon = "0.12"

# Serialization support
serde = { version = "1.0", features = ["derive"], optional = true }

# Symbolic optimization with egglog
egglog = { version = "0.4", optional = true }

[features]
default = ["jit"]
jit = []
serde = ["dep:serde"]
optimization = ["dep:egglog"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
libloading = "0.8"

[[bench]]
name = "expression_optimization"
harness = false

[[bench]]
name = "simple_optimization"
harness = false

 